feature/edit-form
Serdyuk-prog/models_training pull request #9
Opened 2022-05-04 16:25 UTC by hot-play

Переделал формы для создания, удаления и редактирования ботов.
Также подправил мелкие недочеты в виде кавычек и отступов.

2022-05-05 15:43 UTC, alisapopova9 requested changes

2022-05-05 15:43 UTC, alisapopova9 commented on views/botsFunctions/creat.ejs
> +    <fieldset class="modal-dialog">
Куда-то пропал тег формы. Суть fieldset, что он группирует элементы **внутри** формы
Должно быть как-то так:
```html
<form>
    <fieldset>
        <h4>Name:</h4>
        <input class="form form-control" type="text" name="text" id="botName" required />
         <h4>Token:</h4>
         <input class="form form-control" type="text" name="text" id="botToken" required />
    </fieldset>
</form>
```

2022-05-05 15:44 UTC, alisapopova9 commented on views/scripts/script.js
>      var checkInput = document.getElementById("file-upload");
`const checkInput`
Почему стоит уходить от использования var см. [https://learn.javascript.ru/var](https://learn.javascript.ru/var)

2022-05-05 15:45 UTC, alisapopova9 commented on views/scripts/script.js
> +function ChangeLoadButton() {
`function changeLoadButton() { }`
В JavaScript с большой буквы обычно называют либо функцию-конструктор, либо класс, либо компонент (в Реакте), но не обычные методы. Стоит переименовать согласно camelCase

2022-05-05 15:46 UTC, alisapopova9 commented on views/botsFunctions/creat.ejs
> +                <h5 class="modal-title" id="exampleModalLabel">Edit Menu</h5>
Странно, что заголовок модалки семантически "ниже", чем заголовок полей формы внутри модалки (h5 vs h4 ниже)

2022-05-05 15:47 UTC, alisapopova9 commented on views/botsFunctions/creat.ejs
> +                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
Я бы поменяла кнопки местами - сначала идет кнопка действия, а потом кнопка его отмены

2022-05-12 12:10 UTC, alisapopova9 requested changes

2022-05-12 12:10 UTC, alisapopova9 commented on index.js
> +    // axios
Такими большими комментариями лучше не захламлять код. Сейчас получается, что половина файла - это комментарии. Если какая-то часть кода еще не готова, лучше отложить её в stash, а потом, когда нужно, достать её и доработать

2022-05-13 15:19 UTC, alisapopova9 approved these changes

2022-05-15 04:24 UTC, hot-play commented
merge edit form

2022-05-15 04:24 UTC, merged